project:
  type: book

execute: 
  freeze: auto
  error: true

book:
  title: "Lecture 5: R Group Comparison"
  author: "gaoch"
  date: now
  chapters:
    - index.qmd
    - summary.qmd
    - r-basic.qmd
    - datasets-in-r.qmd
    - grouped-data-analysis.qmd
    - grouped-data-analysis-in-action.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: custom
    papersize: a4paper
    fontsize: 9pt
    include-in-header: preamble.tex